apiVersion: v1 
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: production
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 100m
          memory: 50Mi